# Generated by Django 6.0.4 on 2026-04-30 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ptfapp1", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteprofile",
            name="theme",
            field=models.CharField(
                choices=[
                    ("feelnova", "FeelNova — Dark Cosmos"),
                    ("aurora", "Aurora — Deep Forest"),
                    ("crimson", "Crimson — Dark Industrial"),
                ],
                default="feelnova",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="theme_mode",
            field=models.CharField(
                choices=[("dark", "Dark"), ("gray", "Gray")],
                default="dark",
                max_length=10,
            ),
        ),
    ]
