"""
Django settings for ptfconfig project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv # from.env file that has the email and app passwords 

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = []

# For production, set specific domains in environment variable or update here
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost').split(',')



# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "ptfapp1",
    "ptfapp2",
    
    'django.contrib.sites',        # ← required by allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    # 'allauth.socialaccount.providers.zoho',

]


SITE_ID = 1

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    'allauth.account.middleware.AccountMiddleware', 
    'ptfapp2.middleware.RequirePasswordMiddleware', 
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "ptfapp2.middleware.RememberMeMiddleware",
    'allauth.account.middleware.AccountMiddleware',
    ]

AUTHENTICATION_BACKENDS = [
    'ptfapp2.backends.EmailOrUsernameBackend',  # email or username login
    'django.contrib.auth.backends.ModelBackend',# fallback: default Django auth
    'allauth.account.auth_backends.AuthenticationBackend', # for allauth - signup
]
# ─── Email  ───────────────────────────────────────────────────

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST          = 'smtp.gmail.com'          # use smtp.zoho.com if outside India
EMAIL_PORT          = 587
EMAIL_USE_TLS      = True
EMAIL_USE_SSL       = False

EMAIL_HOST_USER    = os.environ['EMAIL_HOST_USER']      # from .env
EMAIL_HOST_PASSWORD = os.environ['EMAIL_HOST_PASSWORD'] # App Password from .env
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

#  admin's email — to receive all contact notifications to admin -
ADMIN_NOTIFICATION_EMAIL = os.environ.get('ADMIN_EMAIL', EMAIL_HOST_USER)

if not EMAIL_HOST_USER or not EMAIL_HOST_PASSWORD:
    raise RuntimeError('ZOHO_EMAIL and ZOHO_APP_PASSWORD must be set in .env or environment for SMTP mail delivery.')


#-----------------------
ROOT_URLCONF = "ptfconfig.urls"

LOGIN_URL          = '/dashboard/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'          # after logout → portfolio root


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "ptfconfig.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Note: Logging configuration removed (was for development DB query debugging)

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# sign up  - for new users #####################################################

# Allauth core behaviour ─ django-allauth ────────────────────────────────────────────
 
ACCOUNT_EMAIL_VERIFICATION = 'none'                                 # no email verification needed
ACCOUNT_LOGIN_METHODS = {'username', 'email'}                       # allow login by either
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']      # email required, no username
ACCOUNT_USER_MODEL_USERNAME_FIELD = 'username'                      # keep Django's default username field
LOGIN_REDIRECT_URL  = '/dashboard/'                                 # adjust to your dashboard URL
LOGOUT_REDIRECT_URL = '/login/'
 
# Point allauth to your custom adapters (already written in ptfapp2/adapters.py)
ACCOUNT_ADAPTER        = 'ptfapp2.adapters.CustomAccountAdapter'
SOCIALACCOUNT_ADAPTER  = 'ptfapp2.adapters.RequirePasswordSocialAdapter'

# ── 4. GOOGLE OAUTH2 PROVIDER CONFIG ────────────────────────────────────────
#  Client ID & Secret come from Google Cloud Console → APIs & Services → Credentials
# stored in .env

SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id':     os.environ.get('GOOGLE_CLIENT_ID', ''),
            'secret':        os.environ.get('GOOGLE_CLIENT_SECRET', ''),
            'key':           '',
        },
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
    }
}

 
# # ── Google + Zoho provider config ─────────────────────────────────────────
# SOCIALACCOUNT_PROVIDERS = {
#     'google': {
#         'SCOPE': ['profile', 'email'],
#         'AUTH_PARAMS': {'access_type': 'online'},
#         'OAUTH_PKCE_ENABLED': True,
#     },
#     'zoho': {
#         'SCOPE': ['AaaServer.profile.READ'],
#     },
# }


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"


USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
